[package]
name = "uni-vanity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
sha3 = "0.10.8"
wasm-bindgen = "0.2.95"
getrandom = { version = "0.2", features = ["js"] }